# Get chrome
image: gitpod/workspace-full-vnc

ports:
    - port: 3000
      visibility: private
      onOpen: open-preview

vscode:
    extensions:
        - esbenp.prettier-vscode
        - vitest.explorer

tasks:
    - init: npm install
      command: npm run dev
